package renderer

import (
	"encoding/json"
	"fmt"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"text/template"
	"time"

	"github.com/DomainCraft/DomainCraft/internal/ir"
	"github.com/DomainCraft/DomainCraft/internal/specmeta"
	"github.com/DomainCraft/DomainCraft/pkg/logger"
	"github.com/DomainCraft/DomainCraft/pkg/textutil"

	"github.com/Masterminds/sprig/v3"
	"gopkg.in/yaml.v3"
)

// Renderer reads bridge.yaml and renders files from IR.
type Renderer struct {
	bridgeDir string
	config    BridgeConfig
	log       *logger.Logger
}

func New(bridgePath string, log *logger.Logger) (*Renderer, error) {
	bridgeDir, configPath := resolveBridgePath(bridgePath)
	data, err := os.ReadFile(configPath)
	if err != nil {
		return nil, fmt.Errorf("read bridge config: %w", err)
	}

	var config BridgeConfig
	if err := yaml.Unmarshal(data, &config); err != nil {
		return nil, fmt.Errorf("parse bridge config: %w", err)
	}
	if config.OutputDir == "" {
		config.OutputDir = "generated"
	}
	return &Renderer{bridgeDir: bridgeDir, config: config, log: log}, nil
}

// delimiters returns the configured template delimiters, defaulting to ["{{", "}}"].
func (r *Renderer) delimiters() (string, string) {
	if len(r.config.Delimiters) >= 2 {
		return r.config.Delimiters[0], r.config.Delimiters[1]
	}
	return "{{", "}}"
}

// applyDelimiters sets custom delimiters on a template if configured.
func (r *Renderer) applyDelimiters(t *template.Template) *template.Template {
	left, right := r.delimiters()
	if left != "{{" || right != "}}" {
		return t.Delims(left, right)
	}
	return t
}

func (r *Renderer) buildFuncMap() (template.FuncMap, error) {
	funcMap := template.FuncMap{}
	for key, value := range sprig.FuncMap() {
		funcMap[key] = value
	}
	// Generic language-agnostic functions
	funcMap["pluralize"] = textutil.Pluralize
	funcMap["singularize"] = textutil.Singularize
	funcMap["pascalcase"] = textutil.PascalCase
	funcMap["camelcase"] = textutil.CamelCase
	funcMap["lowercase"] = strings.ToLower
	funcMap["uppercase"] = strings.ToUpper
	funcMap["humanize"] = func(name string) string {
		return strings.Join(textutil.SplitIdentifier(name), " ")
	}
	funcMap["jsonValue"] = jsonValue
funcMap["fkName"] = func(name string) string {
		// Append "Id" suffix if not already present.
		// Does NOT apply casing — the bridge template controls that via pascalcase/camelcase.
		if !strings.HasSuffix(name, "Id") && !strings.HasSuffix(name, "id") {
			return name + "Id"
		}
		return name
	}
	// rawSeedValue returns the seed value as a raw literal (unquoted numbers, booleans).
	// Language-specific type wrapping (e.g. parsing UUIDs, dates from strings) belongs in templates.
	funcMap["rawSeedValue"] = rawSeedValue
	funcMap["lookupField"] = func(fieldName string, entity ir.IREntity) *ir.IRField {
		for i := range entity.Fields {
			if strings.EqualFold(entity.Fields[i].Name, fieldName) {
				return &entity.Fields[i]
			}
		}
		return nil
	}
	funcMap["hasOwnershipToken"] = func(roles []string) bool {
		return containsOwnerToken(roles)
	}
	// Feature fields are auto-generated by features (audit, soft_delete, etc.)
	// and should be skipped in the main field loop to avoid duplicates
	funcMap["isFeatureField"] = func(name string) bool {
		return specmeta.FeatureFieldNames()[name]
	}
	// isEnumType checks if a DatabaseType is an enum (not a built-in primitive).
	// Works with both plain enum types and array(ENUM) types.
	funcMap["isEnumType"] = func(dbType string) bool {
		return !specmeta.IsPrimitive(specmeta.ParseArrayInner(dbType))
	}
	// enumTypeName returns the raw enum type name from a DatabaseType.
	// For "ProductStatus" -> "ProductStatus", for "array(ProductStatus)" -> "ProductStatus"
	funcMap["enumTypeName"] = func(dbType string) string {
		return specmeta.ParseArrayInner(dbType)
	}

	// Bridge-specific functions
	bridgeFuncs, err := r.getBridgeSpecificFuncs()
	if err != nil {
		return nil, err
	}
	for key, value := range bridgeFuncs {
		funcMap[key] = value
	}
	return funcMap, nil
}

func (r *Renderer) getBridgeSpecificFuncs() (map[string]interface{}, error) {
	bridgeFuncs := make(map[string]interface{})
	// Try to load bridge-specific type mappings from a YAML file inside the bridge dir.
	// This allows bridges to live in separate repos and provide language-specific mappings
	// without changing core code.
	mappingsPath := filepath.Join(r.bridgeDir, "type_mappings.yaml")
	data, err := os.ReadFile(mappingsPath)
	if err == nil {
		var mapping struct {
			Types          map[string]string `yaml:"types"`
			Behaviors      map[string]string `yaml:"behaviors"`
			ValueTypes     []string          `yaml:"value_types"`
			ArrayFormat    string            `yaml:"array_format"`
			EnumNullable   bool              `yaml:"enum_nullable"`
			NullableFormat string            `yaml:"nullable_format"`
			InputTypes     map[string]string `yaml:"input_types"`
		}
		if err := yaml.Unmarshal(data, &mapping); err != nil {
			return nil, fmt.Errorf("parse type_mappings.yaml: %w", err)
		}

		arrayFormat := mapping.ArrayFormat
		if arrayFormat == "" {
			arrayFormat = "%s[]" // fallback: generic array syntax
		}

		nullableSuffix := mapping.NullableFormat
		if nullableSuffix == "" {
			nullableSuffix = "?" // fallback: C#/TS convention
		}

		// wrapNullable applies the bridge-specific nullable format to a type name.
		wrapNullable := func(typeName string) string {
			return typeName + nullableSuffix
		}

		// Build set of value types for quick lookup
		valueTypeSet := make(map[string]bool, len(mapping.ValueTypes))
		for _, vt := range mapping.ValueTypes {
			valueTypeSet[vt] = true
		}

		// wrapArray wraps a type name in the bridge-specific array format.
		wrapArray := func(elementType string) string {
			return fmt.Sprintf(arrayFormat, elementType)
		}

		// languageType maps IR database types to language-specific types via type_mappings.yaml
		bridgeFuncs["languageType"] = func(dbType string, nullable bool) string {
			// Check explicit type mapping first (covers primitives and arrays)
			if mapped, ok := mapping.Types[dbType]; ok {
				if nullable && !specmeta.IsArrayType(dbType) {
					return wrapNullable(mapped)
				}
				return mapped
			}

			inner := specmeta.ParseArrayInner(dbType)

			// Enum type (not a primitive, not in mapping) — format for target language
			if !specmeta.IsPrimitive(strings.ToLower(inner)) {
				formatted := textutil.PascalCase(inner)
				if specmeta.IsArrayType(dbType) {
					return wrapArray(formatted)
				}
				if nullable && mapping.EnumNullable {
					return wrapNullable(formatted)
				}
				return formatted
			}

			// Primitive array not in explicit mapping — wrap inner type
			if specmeta.IsArrayType(dbType) {
				if mapped, ok := mapping.Types[inner]; ok {
					return wrapArray(mapped)
				}
				return wrapArray("string")
			}

			return dbType
		}

		bridgeFuncs["isValueType"] = func(typeName string) bool {
			if mapped, ok := mapping.Types[typeName]; ok {
				return valueTypeSet[mapped]
			}
			return false
		}

		bridgeFuncs["deleteBehaviorName"] = func(value string) string {
			key := strings.ToLower(strings.TrimSpace(value))
			if v, ok := mapping.Behaviors[key]; ok {
				return v
			}
			return textutil.PascalCase(value)
		}

		bridgeFuncs["isPublicPermission"] = func(roles []string) bool {
			for _, r := range roles {
				if r == "*" {
					return true
				}
			}
			return false
		}

		// inputType maps IR database types to UI input components (e.g. "string" -> "Input", "datetime" -> "DatePicker").
		// Bridges that generate UI code define input_types in their type_mappings.yaml.
		if len(mapping.InputTypes) > 0 {
			bridgeFuncs["inputType"] = func(dbType string) string {
				inner := specmeta.ParseArrayInner(dbType)
				if mapped, ok := mapping.InputTypes[inner]; ok {
					return mapped
				}
				if mapped, ok := mapping.InputTypes[dbType]; ok {
					return mapped
				}
				return "Input"
			}
		}
	}
	return bridgeFuncs, nil
}

func (r *Renderer) Render(project *ir.IRProject, outputDir string) ([]string, error) {
	if project == nil {
		return nil, fmt.Errorf("IR project is nil")
	}
	if outputDir == "" {
		outputDir = r.config.OutputDir
	}

	funcMap, err := r.buildFuncMap()
	if err != nil {
		return nil, fmt.Errorf("build template functions: %w", err)
	}

	// Resolve package versions once — avoids repeated HTTP requests per template.
	packages := r.resolvePackages()

	// Parse shared helper templates first (if configured).
	// These define named templates ({{ define "name" }}) that all other templates can call.
	var helpersTemplate *template.Template
	if r.config.Helpers != "" {
		helperPath := filepath.Join(r.bridgeDir, r.config.Helpers)
		helperBytes, err := os.ReadFile(helperPath)
		if err != nil {
			return nil, fmt.Errorf("read helpers %s: %w", r.config.Helpers, err)
		}
		helpersTemplate, err = r.applyDelimiters(template.New("helpers").Funcs(funcMap)).Parse(string(helperBytes))
		if err != nil {
			return nil, fmt.Errorf("parse helpers %s: %w", r.config.Helpers, err)
		}
	}

	writtenFiles := make([]string, 0)
	for _, spec := range r.config.Templates {
		// Check if template should be rendered based on "When" condition
		if !r.shouldRender(spec, project, packages) {
			continue
		}

		sourcePath := filepath.Join(r.bridgeDir, spec.Source)
		tplBytes, err := os.ReadFile(sourcePath)
		if err != nil {
			return nil, fmt.Errorf("read template %s: %w", spec.Source, err)
		}

		tplName := filepath.Base(spec.Source)
		var parsedTemplate *template.Template
		if helpersTemplate != nil {
			// Clone helpers so all named templates are available
			parsedTemplate, err = helpersTemplate.Clone()
			if err != nil {
				return nil, fmt.Errorf("clone helpers for %s: %w", spec.Source, err)
			}
			parsedTemplate, err = r.applyDelimiters(parsedTemplate.New(tplName)).Parse(string(tplBytes))
		} else {
			parsedTemplate, err = r.applyDelimiters(template.New(tplName).Funcs(funcMap)).Parse(string(tplBytes))
		}
		if err != nil {
			return nil, fmt.Errorf("parse template %s: %w", spec.Source, err)
		}

		contexts, err := r.renderContexts(spec.For, project, packages)
		if err != nil {
			return nil, err
		}

		for _, context := range contexts {
			// Check if this specific context should be rendered based on "When" condition
			if !r.shouldRenderContext(spec, context) {
				continue
			}

			for _, targetPattern := range spec.TargetPatterns() {
				renderedTarget, err := renderTemplateString(targetPattern, context, funcMap)
				if err != nil {
					return nil, fmt.Errorf("render target path: %w", err)
				}

				absoluteTarget := filepath.Join(outputDir, filepath.FromSlash(renderedTarget))
				absOutput, _ := filepath.Abs(outputDir)
				absTarget, _ := filepath.Abs(absoluteTarget)
				if !strings.HasPrefix(absTarget, absOutput+string(filepath.Separator)) {
					return nil, fmt.Errorf("template target path escapes output directory: %s", renderedTarget)
				}

				if err := os.MkdirAll(filepath.Dir(absoluteTarget), 0o755); err != nil {
					return nil, fmt.Errorf("create output dir: %w", err)
				}

				file, err := os.Create(absoluteTarget)
				if err != nil {
					return nil, fmt.Errorf("create output file: %w", err)
				}

				if err := parsedTemplate.Execute(file, context); err != nil {
					_ = file.Close()
					_ = os.Remove(absoluteTarget)
					return nil, fmt.Errorf("execute template: %w", err)
				}
				if err := file.Close(); err != nil {
					_ = os.Remove(absoluteTarget)
					return nil, err
				}
				writtenFiles = append(writtenFiles, absoluteTarget)
			}
		}
	}

	return writtenFiles, nil
}

func (r *Renderer) shouldRender(spec TemplateSpec, project *ir.IRProject, packages map[string]string) bool {
	// Entity-level When conditions are checked per-context in shouldRenderContext.
	// Project-level When conditions are checked here.
	if spec.When == "" || spec.For == "entity" {
		return true
	}
	return r.shouldRenderContext(spec, RenderContext{Project: project, Bridge: &r.config, Packages: packages})
}

func (r *Renderer) shouldRenderContext(spec TemplateSpec, context RenderContext) bool {
	if spec.When == "" {
		return true
	}
	switch spec.When {
	case "hasSeed":
		// Only render seed templates if there's actual seed data
		if context.Entity != nil {
			return len(context.Entity.Seed) > 0
		}
		// Project-level: check if any entity has seed data
		if context.Project != nil {
			for _, e := range context.Project.Entities {
				if len(e.Seed) > 0 {
					return true
				}
			}
		}
		return false
	case "hasEnums":
		// Only render enum templates if there are enums defined
		if context.Project != nil && len(context.Project.Enums) > 0 {
			return true
		}
		return false
	case "hasPermissions":
		// Only render permission templates if at least one entity has permissions
		if context.Project != nil {
			for _, e := range context.Project.Entities {
				if e.Permissions != nil {
					return true
				}
			}
		}
		return false
	case "hasOwnerTokens":
		// Only render owner resolver if any entity uses @Owner tokens
		if context.Project != nil {
			for _, e := range context.Project.Entities {
				if e.Permissions != nil {
					if containsOwnerToken(e.Permissions.Read) ||
						containsOwnerToken(e.Permissions.Create) ||
						containsOwnerToken(e.Permissions.Update) ||
						containsOwnerToken(e.Permissions.Delete) {
						return true
					}
				}
			}
		}
		return false
	default:
		return true
	}
}

// warn logs a warning if a logger is configured.
func (r *Renderer) warn(format string, args ...interface{}) {
	if r.log != nil {
		r.log.Warn(format, args...)
	}
}

// containsOwnerToken checks if any role in the slice starts with "@" (ownership token).
func containsOwnerToken(roles []string) bool {
	for _, r := range roles {
		if strings.HasPrefix(r, "@") {
			return true
		}
	}
	return false
}

// resolvePackages resolves all package versions from the package registry.
func (r *Renderer) resolvePackages() map[string]string {
	if len(r.config.RegistryPackages) == 0 {
		return nil
	}

	result := make(map[string]string, len(r.config.RegistryPackages))
	for key, packageID := range r.config.RegistryPackages {
		version, err := resolveRegistryVersion(r.config.RegistryURL, packageID)
		if err != nil {
			r.warn("failed to resolve package %s: %v", packageID, err)
			continue
		}
		if version != "" {
			result[key] = version
		}
	}
	return result
}

func (r *Renderer) renderContexts(scope string, project *ir.IRProject, pkgs map[string]string) ([]RenderContext, error) {
	switch strings.ToLower(strings.TrimSpace(scope)) {
	case "", "entity":
		contexts := make([]RenderContext, 0, len(project.Entities))
		for i := range project.Entities {
			contexts = append(contexts, RenderContext{Project: project, Entity: &project.Entities[i], Bridge: &r.config, Packages: pkgs})
		}
		return contexts, nil
	case "project":
		return []RenderContext{{Project: project, Bridge: &r.config, Packages: pkgs}}, nil
	default:
		return nil, fmt.Errorf("unsupported template scope '%s'", scope)
	}
}

func resolveBridgePath(bridgePath string) (string, string) {
	info, err := os.Stat(bridgePath)
	if err == nil && info.IsDir() {
		return bridgePath, filepath.Join(bridgePath, "bridge.yaml")
	}
	return filepath.Dir(bridgePath), bridgePath
}

func renderTemplateString(pattern string, data any, funcMap template.FuncMap) (string, error) {
	tpl, err := template.New("path").Funcs(funcMap).Parse(pattern)
	if err != nil {
		return "", err
	}
	var builder strings.Builder
	if err := tpl.Execute(&builder, data); err != nil {
		return "", err
	}
	return builder.String(), nil
}

func jsonValue(value any) string {
	encoded, err := json.Marshal(value)
	if err != nil {
		return fmt.Sprintf("%v", value)
	}
	return string(encoded)
}

// rawSeedValue returns the seed value as a raw literal (unquoted numbers, booleans).
// Language-specific type wrapping (e.g. parsing UUIDs, dates from strings) belongs in templates.
func rawSeedValue(value any, dbType string) string {
	strVal := fmt.Sprintf("%v", value)

	if specmeta.IsNumeric(dbType) {
		return strings.Trim(strVal, "\"")
	}
	if dbType == "boolean" {
		strVal = strings.ToLower(strings.Trim(strVal, "\""))
		if strVal == "true" || strVal == "1" {
			return "true"
		}
		return "false"
	}
	return jsonValue(value)
}

var registryClient = &http.Client{Timeout: 5 * time.Second}

// resolveRegistryVersion queries a package registry (e.g. NuGet) for the latest stable version
// of a package. The registryURL template must contain {id} which is replaced with the package ID.
func resolveRegistryVersion(registryURL string, packageID string) (string, error) {
	url := strings.ReplaceAll(registryURL, "{id}", strings.ToLower(packageID))

	req, err := http.NewRequest("GET", url, nil)
	if err != nil {
		return "", err
	}

	resp, err := registryClient.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return "", fmt.Errorf("registry returned %d for %s", resp.StatusCode, packageID)
	}

	var result struct {
		Versions []string `json:"versions"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return "", err
	}

	// Filter for stable versions (no pre-release suffix) and find the maximum.
	var best string
	for _, v := range result.Versions {
		if strings.ContainsAny(v, "-") {
			continue
		}
		if best == "" || versionGreater(v, best) {
			best = v
		}
	}
	if best == "" {
		return "", fmt.Errorf("no stable versions found for %s", packageID)
	}

	return best, nil
}

// versionGreater compares two semver strings and returns true if a > b.
func versionGreater(a, b string) bool {
	aParts := strings.Split(a, ".")
	bParts := strings.Split(b, ".")
	maxLen := len(aParts)
	if len(bParts) > maxLen {
		maxLen = len(bParts)
	}
	for i := 0; i < maxLen; i++ {
		var ai, bi int
		if i < len(aParts) {
			fmt.Sscanf(aParts[i], "%d", &ai)
		}
		if i < len(bParts) {
			fmt.Sscanf(bParts[i], "%d", &bi)
		}
		if ai > bi {
			return true
		}
		if ai < bi {
			return false
		}
	}
	return false
}

