package renderer

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"
	"unicode"

	"domaincraft/internal/ir"

	"github.com/Masterminds/sprig/v3"
	"gopkg.in/yaml.v3"
)

// Renderer reads bridge.yaml and renders files from IR.
type Renderer struct {
	bridgeDir string
	config    BridgeConfig
}

func New(bridgePath string) (*Renderer, error) {
	bridgeDir, configPath := resolveBridgePath(bridgePath)
	data, err := os.ReadFile(configPath)
	if err != nil {
		return nil, fmt.Errorf("read bridge config: %w", err)
	}

	var config BridgeConfig
	if err := yaml.Unmarshal(data, &config); err != nil {
		return nil, fmt.Errorf("parse bridge config: %w", err)
	}
	if config.OutputDir == "" {
		config.OutputDir = "generated"
	}
	return &Renderer{bridgeDir: bridgeDir, config: config}, nil
}

func (r *Renderer) buildFuncMap() template.FuncMap {
	funcMap := template.FuncMap{}
	for key, value := range sprig.FuncMap() {
		funcMap[key] = value
	}
	// Generic language-agnostic functions
	funcMap["pluralize"] = pluralize
	funcMap["singularize"] = singularize
	funcMap["pascalcase"] = pascalCase
	funcMap["camelcase"] = camelCase
	funcMap["lowercase"] = strings.ToLower
	funcMap["uppercase"] = strings.ToUpper
	funcMap["jsonValue"] = jsonValue
	funcMap["hasOwnershipToken"] = func(roles []string) bool {
		for _, r := range roles {
			if strings.HasPrefix(r, "@") {
				return true
			}
		}
		return false
	}
	funcMap["hasPublicToken"] = func(roles []string) bool {
		for _, r := range roles {
			if r == "*" {
				return true
			}
		}
		return false
	}
	// Feature fields are auto-generated by features (audit, soft_delete, etc.)
	// and should be skipped in the main field loop to avoid duplicates
	featureFieldNames := map[string]bool{
		"createdAt": true, "updatedAt": true, // audit
		"createdBy": true, "updatedBy": true, // audit_log
		"deletedAt": true, // soft_delete
		"version":    true, // optimistic_lock
	}
	funcMap["isFeatureField"] = func(name string) bool {
		return featureFieldNames[name]
	}

	// Bridge-specific functions
	bridgeFuncs := r.getBridgeSpecificFuncs()
	for key, value := range bridgeFuncs {
		funcMap[key] = value
	}
	return funcMap
}

func (r *Renderer) getBridgeSpecificFuncs() map[string]interface{} {
	bridgeFuncs := make(map[string]interface{})
	// Try to load bridge-specific type mappings from a YAML file inside the bridge dir.
	// This allows bridges to live in separate repos and provide language-specific mappings
	// without changing core code.
	mappingsPath := filepath.Join(r.bridgeDir, "type_mappings.yaml")
	data, err := os.ReadFile(mappingsPath)
	if err == nil {
		var mapping struct {
			Types      map[string]string `yaml:"types"`
			Behaviors  map[string]string `yaml:"behaviors"`
			ValueTypes []string          `yaml:"value_types"`
		}
		_ = yaml.Unmarshal(data, &mapping)

		// Build set of value types for quick lookup
		valueTypeSet := make(map[string]bool, len(mapping.ValueTypes))
		for _, vt := range mapping.ValueTypes {
			valueTypeSet[vt] = true
		}

		// languageType generic replacement using mapping
		bridgeFuncs["languageType"] = func(goType string, nullable bool) string {
			if mapped, ok := mapping.Types[goType]; ok {
				res := mapped
				if nullable {
					// Check if mapped type is a value type that needs nullable suffix
					if valueTypeSet[mapped] {
						return res + "?"
					}
				}
				return res
			}
			return goType
		}

		bridgeFuncs["isValueType"] = func(typeName string) bool {
			if mapped, ok := mapping.Types[typeName]; ok {
				return valueTypeSet[mapped]
			}
			return false
		}

		bridgeFuncs["deleteBehaviorName"] = func(value string) string {
			key := strings.ToLower(strings.TrimSpace(value))
			if v, ok := mapping.Behaviors[key]; ok {
				return v
			}
			return pascalCase(strings.ReplaceAll(strings.ReplaceAll(value, "_", " "), "-", " "))
		}
	}
	return bridgeFuncs
}

func (r *Renderer) Render(project *ir.IRProject, outputDir string) ([]string, error) {
	if project == nil {
		return nil, fmt.Errorf("IR project is nil")
	}
	if outputDir == "" {
		outputDir = r.config.OutputDir
	}

	funcMap := r.buildFuncMap()

	writtenFiles := make([]string, 0)
	for _, spec := range r.config.Templates {
		// Check if template should be rendered based on "When" condition
		if !r.shouldRender(spec, project) {
			continue
		}

		sourcePath := filepath.Join(r.bridgeDir, spec.Source)
		tplBytes, err := os.ReadFile(sourcePath)
		if err != nil {
			return nil, fmt.Errorf("read template %s: %w", spec.Source, err)
		}

		parsedTemplate, err := template.New(filepath.Base(spec.Source)).Funcs(funcMap).Parse(string(tplBytes))
		if err != nil {
			return nil, fmt.Errorf("parse template %s: %w", spec.Source, err)
		}

		contexts, err := renderContexts(spec.For, project)
		if err != nil {
			return nil, err
		}

		for _, context := range contexts {
			// Check if this specific context should be rendered based on "When" condition
			if !r.shouldRenderContext(spec, context) {
				continue
			}

			for _, targetPattern := range spec.TargetPatterns() {
				renderedTarget, err := renderTemplateString(targetPattern, context, funcMap)
				if err != nil {
					return nil, fmt.Errorf("render target path: %w", err)
				}

				absoluteTarget := filepath.Join(outputDir, filepath.FromSlash(renderedTarget))
				if err := os.MkdirAll(filepath.Dir(absoluteTarget), 0o755); err != nil {
					return nil, fmt.Errorf("create output dir: %w", err)
				}

				file, err := os.Create(absoluteTarget)
				if err != nil {
					return nil, fmt.Errorf("create output file: %w", err)
				}

				if err := parsedTemplate.Execute(file, context); err != nil {
					_ = file.Close()
					return nil, fmt.Errorf("execute template: %w", err)
				}
				if err := file.Close(); err != nil {
					return nil, err
				}
				writtenFiles = append(writtenFiles, absoluteTarget)
			}
		}
	}

	return writtenFiles, nil
}

func (r *Renderer) shouldRender(spec TemplateSpec, project *ir.IRProject) bool {
	if spec.When == "" {
		return true
	}
	// For entity templates, we need to check per context
	if spec.For == "entity" {
		return true // Will be checked in shouldRenderContext
	}
	// For project templates, always render
	return true
}

func (r *Renderer) shouldRenderContext(spec TemplateSpec, context RenderContext) bool {
	if spec.When == "" {
		return true
	}
	switch spec.When {
	case "hasSeed":
		// Only render seed templates if there's actual seed data
		if context.Entity != nil && len(context.Entity.Seed) > 0 {
			return true
		}
		return false
	case "hasEnums":
		// Only render enum templates if there are enums defined
		if context.Project != nil && len(context.Project.Enums) > 0 {
			return true
		}
		return false
	default:
		return true
	}
}

func renderContexts(scope string, project *ir.IRProject) ([]RenderContext, error) {
	switch strings.ToLower(strings.TrimSpace(scope)) {
	case "", "entity":
		contexts := make([]RenderContext, 0, len(project.Entities))
		for i := range project.Entities {
			contexts = append(contexts, RenderContext{Project: project, Entity: &project.Entities[i]})
		}
		return contexts, nil
	case "project":
		return []RenderContext{{Project: project}}, nil
	default:
		return nil, fmt.Errorf("unsupported template scope '%s'", scope)
	}
}

func resolveBridgePath(bridgePath string) (string, string) {
	info, err := os.Stat(bridgePath)
	if err == nil && info.IsDir() {
		return bridgePath, filepath.Join(bridgePath, "bridge.yaml")
	}
	return filepath.Dir(bridgePath), bridgePath
}

func renderTemplateString(pattern string, data any, funcMap template.FuncMap) (string, error) {
	tpl, err := template.New("path").Funcs(funcMap).Parse(pattern)
	if err != nil {
		return "", err
	}
	var builder strings.Builder
	if err := tpl.Execute(&builder, data); err != nil {
		return "", err
	}
	return builder.String(), nil
}

func jsonValue(value any) string {
	encoded, err := json.Marshal(value)
	if err != nil {
		return fmt.Sprintf("%v", value)
	}
	return string(encoded)
}

func camelCase(value string) string {
	value = pascalCase(value)
	if value == "" {
		return ""
	}
	return strings.ToLower(value[:1]) + value[1:]
}

func pluralize(value string) string {
	lower := strings.ToLower(value)
	if strings.HasSuffix(lower, "y") && len(value) > 1 {
		return value[:len(value)-1] + "ies"
	}
	if strings.HasSuffix(lower, "s") {
		return value + "es"
	}
	return value + "s"
}

func singularize(value string) string {
	lower := strings.ToLower(value)
	if strings.HasSuffix(lower, "ies") && len(value) > 3 {
		return value[:len(value)-3] + "y"
	}
	if strings.HasSuffix(lower, "ses") && len(value) > 3 {
		return value[:len(value)-2]
	}
	if strings.HasSuffix(lower, "s") && len(value) > 1 {
		return value[:len(value)-1]
	}
	return value
}

func pascalCase(value string) string {
	if value == "" {
		return ""
	}
	parts := splitIdentifierParts(value)
	for i := range parts {
		if parts[i] == "" {
			continue
		}
		parts[i] = strings.ToUpper(parts[i][:1]) + strings.ToLower(parts[i][1:])
	}
	return strings.Join(parts, "")
}

func splitIdentifierParts(value string) []string {
	var parts []string
	var current []rune
	var previous rune
	for i, r := range value {
		if r == '_' || r == '-' || r == ' ' {
			if len(current) > 0 {
				parts = append(parts, string(current))
				current = current[:0]
			}
			previous = 0
			continue
		}

		if i > 0 && unicode.IsUpper(r) && previous != 0 && unicode.IsLower(previous) {
			parts = append(parts, string(current))
			current = current[:0]
		}

		current = append(current, r)
		previous = r
	}

	if len(current) > 0 {
		parts = append(parts, string(current))
	}

	if len(parts) == 0 {
		return []string{value}
	}
	return parts
}
